apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-foo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-foo-app
  template:
    metadata:
      labels:
        app: kube-foo-app
    spec:
      containers:
        - name: kube-foo-app
          image: h0tw4t3r/foo:0.1.0
          ports:
            - containerPort: 3001
              protocol: TCP
